### ISSUE TITLE
Acuparse Support

### ISSUE THREAD

**Issue by maxwellpower** [bpaauwe/WeatherPoly#1]
Hi,

I'm the author of Acuparse. I was checking out my GitHub logs and came across a link back to forums discussing WeatherPoly. Seems someone asked about Acuparse support. Anyway, it looks like it should be fairly simple to provide support for WeatherPoly inside of Acuparse. Since your just looking for a GET and this is already being done to send readings everywhere else.

What I don't totally understand is what is going on here specifically. How can I make it as easy as possible to pass data to WeatherPoly? I see mentions of mappings. Is there anything special I can do to make it as plug and play as possible?

**Comment by bpaauwe** [comment]
Hi Maxwell,

Thanks for reaching out.  I've not really looked closely at acuparse, but it seems like a really nice package. When I switched over to an Access from the smarthub, I also installed a receiver on a RPi and started capturing the data direct from the 433Mhz signals instead of trying to intercept data from the Access device.

WeatherPoly runs a small simple web server and waits for GET requests.  Right now I have it parsing the formats that MeteoBridge and Cumulus send, but adding support for additional ones is pretty easy.

Ideally the request would use some path that I can use to identify it followed by query key/value pairs. For example:
/acuparse?temperature=23&pressure=1003 ...

The user then has to create a configuration mapping that maps the internal WeatherPoly value names to the key names used by the provider (acuparse in this case).  So to map the temperature above the user would add "temperature-main = temperature".  

So for me to add support, I just need to know what the request string will look like, what all the possible key names are and what units are used.

So it may be simple as creating a configuration for PWS or WU but use the WeatherPoly IP address instead of PWS or WU host.  I was looking at the config and it would be something like:
`'wp' => (object)array(
            'enabled' => false, // true or false
            'id' => '', // Station ID
            'password' => '', // Password
            'url' => 'http://192.168.1.10/acuparse', // Server URL
        ),
`
And you could reuse the same code section used for WU or PWS.  Software packages like Cumulus allow the user to create a generic upload URL with whatever data they want to send, it doesn't seem that hard to add a feature like that to acuparse. That would probably be better than a dedicated code block in cron.php just for WeatherPoly as I suspect the number of people interested in this is pretty small

**Comment by maxwellpower** [comment]
Thanks for the info.

For Version 2.7.0, I added a "Generic" server which will send WU formatted updates to a user-defined system. In theory, this should work.

I also added a doc for WeatherPoly which includes what I believe the mappings should be.
[https://github.com/acuparse/acuparse/blob/41f31a101d1db339740ad9d1c77d6221acc5b7ec/docs/external/generic/WeatherPoly.md](https://github.com/acuparse/acuparse/blob/41f31a101d1db339740ad9d1c77d6221acc5b7ec/docs/external/generic/WeatherPoly.md)

**Comment by bpaauwe** [comment]
Thanks!  It looks correct to me.  I added support in version 0.1.5 to parse the data so it should work end-to-end now.
